obj-$(CONFIG_MTK_SOC_THERMAL)	+= auxadc_thermal.o
obj-$(CONFIG_MTK_LVTS_THERMAL)	+= lvts_thermal.o virtual_temp.o
obj-$(CONFIG_MTK_LVTS_THERMAL)	+= soc_temp_lvts.o
obj-$(CONFIG_MTK_LVTS_THERMAL)  += soc_temp_lvts_mt8189.o
obj-$(CONFIG_MTK_LVTS_THERMAL)	+= soc_temp_lvts_mt8192.o
obj-$(CONFIG_MTK_LVTS_THERMAL)	+= soc_temp_lvts_mt8196.o
obj-$(CONFIG_MTK_LVTS_THERMAL)	+= thermal_interface.o
