# SPDX-License-Identifier: (GPL-2.0 OR MIT)

obj-$(CONFIG_MTK_CM_MGR) += cm_mgr/
obj-$(CONFIG_MTK_SLBC) += slbc/
obj-$(CONFIG_MTK_MMDVFS) += mmdvfs/
obj-$(CONFIG_MTK_MMDEBUG) += mmdebug/
obj-$(CONFIG_MTK_MMINFRA) += mminfra/
obj-$(CONFIG_INTERCONNECT_MTK_EXTENSION) += mtk-interconnect/
obj-$(CONFIG_MTK_DVFSRC_HELPER) += dvfsrc/
