# SPDX-License-Identifier: GPL-2.0-only

ccflags-y += -I$(src)
ccflags-y += -I$(srctree)/drivers/soc/mediatek/
ccflags-y += -I$(srctree)/drivers/remoteproc/vcp
ccflags-y += -I$(srctree)/drivers/remoteproc/vcp/include
obj-$(CONFIG_MTK_MMDEBUG) += mtk-mmdebug-vcp.o
