# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_INTERCONNECT_MTK_EMI) += mtk-emi.o
obj-$(CONFIG_INTERCONNECT_MTK_MMQOS_MT8196) += mmqos-mt8196.o
obj-$(CONFIG_INTERCONNECT_MTK_MMQOS_COMMON) += mmqos-common.o
mmqos-common-objs += mmqos-mtk.o mmqos-hrt.o mmqos-vcp.o
